version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodbToDoApp
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongodb/data:/data/db